version: "2"

services:
  api-service-alert-publisher:
    image: api-service-alert-publisher:latest
    networks:
    - monitoring_alert_publisher_default
    container_name: api-service-alert-publisher
    volumes:
    - ./src/:/app/src/
    - ./test/:/app/test/
    - .eslintrc.json:/app/.eslintrc.json
    - ./package.json:/app/package.json
    - ${HOME}/.npmrc:/app/.npmrc
    ports:
    - 8080:8080
    environment:
      PUBLIC_URL: "localhost"
      SERVER_PORT: 8080
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: "monitoringAlert"
      REDIS_NAMESPACE: "rsmq"
      KAFKA_PROXY_ENDPOINT: "http://kafka:8082"
      KAFKA_SCHEMA_REGISTRY_ENDPOINT: "http://kafka:8081"
      SPLUNK_CHANNEL_NAME: "monitoring-alert"
  redis:
    image: "redis:4.0.10-alpine"
    ports:
    - 6379:6379
    networks:
    - monitoring_alert_publisher_default

networks:
  monitoring_alert_publisher_default: